---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: personal-website
type: Opaque
stringData:
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: personal-website
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${POSTGRES_STORAGE_SIZE}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: personal-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:${POSTGRES_VERSION}
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: postgres-secret
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "${POSTGRES_MEMORY_REQUEST}"
              cpu: "${POSTGRES_CPU_REQUEST}"
            limits:
              memory: "${POSTGRES_MEMORY_LIMIT}"
              cpu: "${POSTGRES_CPU_LIMIT}"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: personal-website
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
