apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: frontend-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: frontend-src
  filterTags:
      pattern: "^prod-.*$"
  policy:
    semver:
      range: '>=1.0.0'
